### ISSUE TITLE
RFDuino library expects g++ compiler, which is no longer present

### ISSUE THREAD

**Issue by chipaudette** [OpenBCI/OpenBCI_Radios#1]
The RFDuino library, via its "platform.txt" configuration file, expects there to be a g++ compiler.  In Arduino 1.5.7 and 1.5.8 for Windows (maybe also other platforms, and maybe also earlier versions), the g++ compiler is no longer present.  So, the code won't compile.

A workaround has been found using the gcc compiler through the Arduino toolchain (presumably in place of the g++ compiler).  See:

 http://openbci.com/forum/index.php?p=/discussion/259/missing-compiler-when-re-programming-the-rfduinos-dongle-and-openbci-device#latest

Can this be fixed so that it works without users having to edit any files?

Chip

**Comment by biomurph** [comment]
Changed the platform.txt file so that it points to the right compiler path. 
Also verified that this will work on Mac and Windows
